apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: solo-boss-ai-platform
  annotations:
    # Google Cloud Run annotations
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Resource limits optimized for Next.js
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1000m"
        # Scaling configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "100"
        # Request timeout
        run.googleapis.com/timeout: "900s"
    spec:
      containerConcurrency: 1000
      containers:
      - name: solo-boss-ai-platform
        image: gcr.io/PROJECT_ID/solo-boss-ai-platform:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        # Add your environment variables here
        # - name: DATABASE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: app-secrets
        #       key: database-url
        resources:
          limits:
            cpu: "1000m"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        # Health checks
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
