apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: soloboss-ai-platform
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        # Execution environment
        run.googleapis.com/execution-environment: gen2
        # Set CPU and memory limits
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "2"
        # Auto-scaling configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: us-central1-docker.pkg.dev/soloboss-ai-v3/soloboss-ai-platform/soloboss-ai-platform:cache-bust-20250818-041321
        ports:
        - containerPort: 3000
        env:
        # Node.js environment
        - name: NODE_ENV
          value: "production"
        - name: HOSTNAME
          value: "0.0.0.0"
        # Stack Auth Configuration
        - name: NEXT_PUBLIC_STACK_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: NEXT_PUBLIC_STACK_PROJECT_ID
              key: latest
        - name: NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY
          valueFrom:
            secretKeyRef:
              name: NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY
              key: latest
        - name: STACK_SECRET_SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: STACK_SECRET_SERVER_KEY
              key: latest
        # Database Configuration
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: DATABASE_URL
              key: latest
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: JWT_SECRET
              key: latest
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: ENCRYPTION_KEY
              key: latest
        # AI Services
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: OPENAI_API_KEY
              key: latest
        # Email Services
        - name: RESEND_API_KEY
          valueFrom:
            secretKeyRef:
              name: RESEND_API_KEY
              key: latest
        - name: FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: FROM_EMAIL
              key: latest
        # App Configuration
        - name: NEXT_PUBLIC_APP_URL
          valueFrom:
            secretKeyRef:
              name: NEXT_PUBLIC_APP_URL
              key: latest
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "512Mi"
        # Health check configuration (readinessProbe not supported in this project)
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
