
import { CompetitorReport, WarRoomResponse } from "../types";
import { AGENTS } from "../constants";

export const downloadMarkdown = (filename: string, content: string) => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename.replace(/\s+/g, '_').toLowerCase()}_${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

export const generateCompetitorMarkdown = (report: CompetitorReport): string => {
    return `
# CLASSIFIED INTELLIGENCE REPORT: ${report.competitorName.toUpperCase()}
**Date:** ${new Date(report.generatedAt).toLocaleString()}
**Threat Level:** ${report.threatLevel}
**Author:** SoloSuccess AI

---

## 1. MISSION BRIEF
${report.missionBrief || 'No mission brief available.'}

## 2. THREAT MATRIX
- **Innovation:** ${report.metrics?.innovation || 'N/A'}/100
- **Market Presence:** ${report.metrics?.marketPresence || 'N/A'}/100
- **UX Quality:** ${report.metrics?.ux || 'N/A'}/100
- **Pricing Power:** ${report.metrics?.pricing || 'N/A'}/100
- **Velocity:** ${report.metrics?.velocity || 'N/A'}/100

## 3. INTERCEPTED INTEL
${(report.intel || report.marketingChannels || []).map(i => `- ${i}`).join('\n')}

## 4. CRITICAL VULNERABILITIES
${(report.vulnerabilities || report.weaknesses || []).map(v => `- [WEAKNESS] ${v}`).join('\n')}

## 5. DEFENSIVE STRENGTHS
${report.strengths.map(s => `- [STRENGTH] ${s}`).join('\n')}

---
*Generated by SoloSuccess AI - The Virtual Executive Team*
    `.trim();
};

export const generateWarRoomMarkdown = (topic: string, session: WarRoomResponse): string => {
    return `
# WAR ROOM TRANSCRIPT
**Topic:** ${topic}
**Date:** ${new Date().toLocaleString()}

---

## EXECUTIVE SUMMARY (CONSENSUS)
${session.consensus}

---

## ACTION PLAN
${session.actionPlan.map((step, i) => `${i + 1}. ${step}`).join('\n')}

---

## TRANSCRIPT

${session.dialogue.map(entry => `**${AGENTS[entry.speaker].name.toUpperCase()}:** ${entry.text}`).join('\n\n')}

---
*Generated by SoloSuccess AI*
    `.trim();
};