
import React, { useState } from 'react';
import { Scale, FileText, ShieldAlert, CheckCircle2, PenTool, AlertTriangle, Loader2, Copy, Check, Hand } from 'lucide-react';
import { draftLegalDoc, analyzeContract } from '../services/geminiService';
import { LegalDocType, LegalAnalysis } from '../types';
import { addXP, showToast } from '../services/gameService';
import { soundService } from '../services/soundService';

export const TheIronclad: React.FC = () => {
    const [activeTab, setActiveTab] = useState<'draft' | 'review'>('draft');
    const [disclaimerAgreed, setDisclaimerAgreed] = useState(false);

    // Draft State
    const [docType, setDocType] = useState<LegalDocType>('NDA');
    const [docDetails, setDocDetails] = useState('');
    const [draftResult, setDraftResult] = useState<string | null>(null);

    // Review State
    const [contractText, setContractText] = useState('');
    const [analysisResult, setAnalysisResult] = useState<LegalAnalysis | null>(null);

    const [loading, setLoading] = useState(false);
    const [copied, setCopied] = useState(false);

    const handleAgree = () => {
        // PRODUCTION NOTE: IMPORTANT LEGAL LIABILITY
        // In production, you MUST log this acceptance to a persistent database with a timestamp, user ID, and IP address.
        // Example: await db.auditLog.create({ user: userId, action: 'ACCEPTED_LEGAL_DISCLAIMER', timestamp: new Date() });
        setDisclaimerAgreed(true);
        soundService.playSuccess();
    };

    const handleDraft = async () => {
        if (!docDetails.trim()) return;
        setLoading(true);
        setDraftResult(null);
        soundService.playClick();

        const result = await draftLegalDoc(docType, docDetails);
        if (result) {
            setDraftResult(result);
            // PRODUCTION NOTE: Consider saving generated legal docs to 'The Vault' automatically here.
            const { leveledUp } = await addXP(50);
            showToast("CONTRACT DRAFTED", "Document generated successfully.", "xp", 50);
            if (leveledUp) showToast("RANK UP!", "New founder level reached.", "success");
            soundService.playSuccess();
        }
        setLoading(false);
    };

    const handleAnalyze = async () => {
        if (!contractText.trim()) return;
        setLoading(true);
        setAnalysisResult(null);
        soundService.playClick();

        const result = await analyzeContract(contractText);
        if (result) {
            setAnalysisResult(result);
            const { leveledUp } = await addXP(60);
            showToast("ANALYSIS COMPLETE", "Risk assessment generated.", "xp", 60);
            if (leveledUp) showToast("RANK UP!", "New founder level reached.", "success");
            soundService.playSuccess();
        }
        setLoading(false);
    };

    const copyToClipboard = (text: string) => {
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
        soundService.playClick();
    };

    if (!disclaimerAgreed) {
        return (
            <div className="min-h-[85vh] flex flex-col items-center justify-center animate-in fade-in duration-500 p-4">
                <div className="max-w-lg w-full bg-zinc-900 border-2 border-red-900/50 p-6 md:p-8 rounded-xl relative overflow-hidden shadow-2xl">
                    <div className="absolute inset-0 bg-red-950/10 pointer-events-none"></div>
                    <div className="relative z-10 flex flex-col items-center text-center">
                        <div className="w-16 h-16 bg-red-900/20 rounded-full flex items-center justify-center text-red-500 mb-6 border border-red-900/50">
                            <Hand size={32} />
                        </div>

                        <h2 className="text-2xl font-black text-white mb-2 uppercase tracking-tight">Compliance Gate</h2>
                        <p className="text-red-400 font-mono text-sm mb-6 uppercase tracking-widest">Legal Disclaimer Required</p>

                        <div className="bg-black border border-zinc-800 p-4 rounded-lg text-zinc-300 text-sm leading-relaxed text-left mb-8 font-mono">
                            <p className="mb-3">
                                <strong className="text-white">SOLOSUCCESS AI IS NOT A LAW FIRM.</strong>
                            </p>
                            <p className="mb-3">
                                The output provided by the "Lumi" agent is generated by artificial intelligence for informational purposes only. It does <strong className="text-white">NOT</strong> constitute legal advice, legal representation, or create an attorney-client relationship.
                            </p>
                            <p>
                                You should always consult with a qualified attorney licensed in your jurisdiction before signing any legal documents or making binding business decisions.
                            </p>
                        </div>

                        <button
                            onClick={handleAgree}
                            className="w-full py-4 bg-red-600 hover:bg-red-500 text-white font-bold uppercase tracking-widest rounded transition-all shadow-lg shadow-red-900/20"
                        >
                            I Acknowledge & Agree
                        </button>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-[85vh] flex flex-col animate-in fade-in duration-500">
            {/* Header */}
            <div className="mb-6 flex items-end justify-between border-b border-zinc-800 pb-6">
                <div>
                    <div className="flex items-center gap-2 text-violet-400 font-mono text-xs font-bold uppercase tracking-widest mb-2">
                        <Scale size={14} /> Legal & Compliance
                    </div>
                    <h2 className="text-4xl font-black text-white tracking-tighter">THE IRONCLAD</h2>
                    <p className="text-zinc-400 mt-2">Automated legal counsel provided by <span className="text-violet-400 font-bold">Lumi</span>.</p>
                </div>
            </div>

            {/* Tabs */}
            <div className="flex gap-4 mb-8 border-b border-zinc-800 overflow-x-auto pb-1 scrollbar-hide">
                <button
                    onClick={() => setActiveTab('draft')}
                    className={`pb-4 px-4 text-sm font-bold uppercase tracking-wider transition-all border-b-2 whitespace-nowrap ${activeTab === 'draft' ? 'border-violet-500 text-violet-400' : 'border-transparent text-zinc-500 hover:text-zinc-300'}`}
                >
                    <span className="flex items-center gap-2"><PenTool size={16} /> Drafter</span>
                </button>
                <button
                    onClick={() => setActiveTab('review')}
                    className={`pb-4 px-4 text-sm font-bold uppercase tracking-wider transition-all border-b-2 whitespace-nowrap ${activeTab === 'review' ? 'border-violet-500 text-violet-400' : 'border-transparent text-zinc-500 hover:text-zinc-300'}`}
                >
                    <span className="flex items-center gap-2"><ShieldAlert size={16} /> Loophole Scanner</span>
                </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 h-full">

                {/* Input Section */}
                <div className="flex flex-col gap-4">
                    <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-6 flex-1 flex flex-col">

                        {activeTab === 'draft' ? (
                            <>
                                <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-widest mb-4">Document Configuration</h3>
                                <div className="space-y-4 flex-1">
                                    <div>
                                        <label className="text-xs font-bold text-zinc-400 block mb-2">Document Type</label>
                                        <select
                                            value={docType}
                                            onChange={(e) => setDocType(e.target.value as LegalDocType)}
                                            className="w-full bg-black border border-zinc-700 rounded p-3 text-white focus:border-violet-500"
                                        >
                                            <option value="NDA">Non-Disclosure Agreement (NDA)</option>
                                            <option value="Contractor Agreement">Independent Contractor Agreement</option>
                                            <option value="SaaS Terms of Service">SaaS Terms of Service</option>
                                            <option value="Privacy Policy">Privacy Policy</option>
                                            <option value="Offer Letter">Employee Offer Letter</option>
                                        </select>
                                    </div>
                                    <div className="flex-1 flex flex-col">
                                        <label className="text-xs font-bold text-zinc-400 block mb-2">Key Details (Parties, Dates, Jurisdiction)</label>
                                        <textarea
                                            value={docDetails}
                                            onChange={(e) => setDocDetails(e.target.value)}
                                            className="w-full flex-1 bg-black border border-zinc-700 rounded p-4 text-sm text-white resize-none focus:border-violet-500"
                                            placeholder="e.g. Between Acme Corp (Delaware) and John Doe. Effective Jan 1st. Standard confidentiality terms. NY Law."
                                        />
                                    </div>
                                </div>
                                <button
                                    onClick={handleDraft}
                                    disabled={loading || !docDetails.trim()}
                                    className="mt-6 w-full py-3 bg-violet-700 hover:bg-violet-600 text-white rounded font-bold uppercase tracking-widest transition-all disabled:opacity-50 flex items-center justify-center gap-2 shadow-lg shadow-violet-900/20"
                                >
                                    {loading ? <Loader2 size={16} className="animate-spin" /> : <><FileText size={16} /> Generate Document</>}
                                </button>
                            </>
                        ) : (
                            <>
                                <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-widest mb-4">Contract Analysis</h3>
                                <div className="flex-1 flex flex-col">
                                    <textarea
                                        value={contractText}
                                        onChange={(e) => setContractText(e.target.value)}
                                        className="w-full flex-1 bg-black border border-zinc-700 rounded p-4 text-sm text-white resize-none focus:border-violet-500 font-mono"
                                        placeholder="Paste the full contract text here for analysis..."
                                    />
                                </div>
                                <button
                                    onClick={handleAnalyze}
                                    disabled={loading || !contractText.trim()}
                                    className="mt-6 w-full py-3 bg-red-900/50 hover:bg-red-900 text-red-200 border border-red-900 rounded font-bold uppercase tracking-widest transition-all disabled:opacity-50 flex items-center justify-center gap-2"
                                >
                                    {loading ? <Loader2 size={16} className="animate-spin" /> : <><ShieldAlert size={16} /> Scan for Risks</>}
                                </button>
                            </>
                        )}

                    </div>
                </div>

                {/* Output Section */}
                <div className="bg-zinc-950 border border-zinc-800 rounded-xl p-6 relative overflow-hidden flex flex-col min-h-[500px]">
                    {!draftResult && !analysisResult && !loading && (
                        <div className="flex-1 flex flex-col items-center justify-center text-zinc-700 opacity-50">
                            <Scale size={64} strokeWidth={1} />
                            <p className="mt-4 font-mono uppercase tracking-widest text-sm">Awaiting Legal Input</p>
                        </div>
                    )}

                    {loading && (
                        <div className="flex-1 flex flex-col items-center justify-center text-violet-500">
                            <Loader2 size={48} className="animate-spin mb-4" />
                            <p className="font-mono uppercase tracking-widest animate-pulse">Consulting Lumi (The Sentinel)...</p>
                        </div>
                    )}

                    {activeTab === 'draft' && draftResult && (
                        <div className="flex-1 flex flex-col animate-in fade-in slide-in-from-bottom-4 duration-500 relative">
                            <div className="flex justify-between items-center mb-4 border-b border-zinc-800 pb-4">
                                <h3 className="font-bold text-white flex items-center gap-2"><CheckCircle2 className="text-emerald-500" size={18} /> Draft Ready</h3>
                                <button onClick={() => copyToClipboard(draftResult)} className="text-xs font-bold text-zinc-500 hover:text-white flex items-center gap-2 uppercase">
                                    {copied ? <Check size={14} /> : <Copy size={14} />} {copied ? 'Copied' : 'Copy Text'}
                                </button>
                            </div>
                            <div className="flex-1 bg-black border border-zinc-800 rounded-lg p-4 overflow-y-auto custom-scrollbar">
                                <pre className="whitespace-pre-wrap text-zinc-300 font-mono text-sm leading-relaxed">
                                    {draftResult}
                                </pre>
                            </div>
                            <p className="text-[10px] text-red-500 font-mono mt-2 text-center uppercase">* Verify with legal counsel before use.</p>
                        </div>
                    )}

                    {activeTab === 'review' && analysisResult && (
                        <div className="flex-1 flex flex-col animate-in fade-in slide-in-from-bottom-4 duration-500">
                            <div className="flex items-start justify-between mb-6 pb-4 border-b border-zinc-800">
                                <div>
                                    <h3 className="text-lg font-bold text-white">Contract Verdict</h3>
                                    <p className="text-zinc-400 text-sm italic">"{analysisResult.verdict}"</p>
                                </div>
                                <div className="text-center bg-zinc-900 p-3 rounded border border-zinc-800">
                                    <div className="text-[10px] font-bold text-zinc-500 uppercase">Safety Score</div>
                                    <div className={`text-3xl font-black ${analysisResult.safetyScore > 80 ? 'text-emerald-500' : analysisResult.safetyScore > 50 ? 'text-yellow-500' : 'text-red-500'}`}>
                                        {analysisResult.safetyScore}
                                    </div>
                                </div>
                            </div>

                            <div className="space-y-6 overflow-y-auto custom-scrollbar flex-1 pr-2">
                                <div className="bg-red-950/10 border border-red-900/30 p-4 rounded-lg">
                                    <h4 className="text-xs font-bold text-red-500 uppercase tracking-widest mb-3 flex items-center gap-2">
                                        <AlertTriangle size={14} /> Critical Risks
                                    </h4>
                                    <ul className="space-y-2">
                                        {analysisResult.criticalRisks.map((risk, i) => (
                                            <li key={i} className="text-sm text-zinc-300 flex items-start gap-2">
                                                <span className="text-red-500 font-bold">×</span> {risk}
                                            </li>
                                        ))}
                                        {analysisResult.criticalRisks.length === 0 && <li className="text-sm text-zinc-500 italic">No critical risks detected.</li>}
                                    </ul>
                                </div>

                                <div className="bg-slate-900/30 border border-slate-800 p-4 rounded-lg">
                                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-3 flex items-center gap-2">
                                        <FileText size={14} /> Suggestions
                                    </h4>
                                    <ul className="space-y-2">
                                        {analysisResult.suggestions.map((sug, i) => (
                                            <li key={i} className="text-sm text-zinc-300 flex items-start gap-2">
                                                <span className="text-slate-500 font-bold">›</span> {sug}
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    )}

                </div>
            </div>
        </div>
    );
};
