
-- Create the table for template categories
CREATE TABLE template_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  icon TEXT,
  description TEXT
);

-- Create the table for templates
CREATE TABLE templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  slug TEXT NOT NULL UNIQUE,
  is_interactive BOOLEAN DEFAULT FALSE NOT NULL,
  required_role TEXT NOT NULL,
  category_id BIGINT REFERENCES template_categories(id)
);

-- Enable RLS
ALTER TABLE template_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public read access
CREATE POLICY "Allow public read access" ON template_categories FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON templates FOR SELECT USING (true);
