-- Complete SoloSuccess AI Database Schema
-- This file creates all necessary tables for the platform

-- =============================================
-- CORE USER TABLES
-- =============================================

-- Users table (profiles)
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    full_name TEXT,
    avatar_url TEXT,
    company_name TEXT,
    industry TEXT,
    business_type TEXT,
    phone TEXT,
    website TEXT,
    bio TEXT,
    timezone TEXT DEFAULT 'America/New_York',
    notification_preferences JSONB DEFAULT '{"email": true, "push": true, "marketing": false}',
    onboarding_completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- GOALS AND TASKS MANAGEMENT
-- =============================================

-- Goals table
CREATE TABLE IF NOT EXISTS goals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high')),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'in-progress', 'completed', 'cancelled')),
    progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    deadline DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tasks table
CREATE TABLE IF NOT EXISTS tasks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    goal_id UUID REFERENCES goals(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT,
    priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high')),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'in-progress', 'completed', 'cancelled')),
    due_date TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- AI AGENTS AND CONVERSATIONS
-- =============================================

-- AI Agents table
CREATE TABLE IF NOT EXISTS ai_agents (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    description TEXT,
    personality TEXT,
    capabilities TEXT[],
    accent_color TEXT,
    system_prompt TEXT,
    model_preference TEXT DEFAULT 'gpt-4',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Conversations table
CREATE TABLE IF NOT EXISTS conversations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    agent_name TEXT NOT NULL,
    title TEXT,
    messages JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- DOCUMENT MANAGEMENT
-- =============================================

-- Documents table
CREATE TABLE IF NOT EXISTS documents (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    filename TEXT NOT NULL,
    original_filename TEXT NOT NULL,
    file_size INTEGER NOT NULL,
    mime_type TEXT NOT NULL,
    file_data BYTEA NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- TEMPLATE SYSTEM
-- =============================================

-- Template categories table
CREATE TABLE IF NOT EXISTS template_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    icon TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Templates table
CREATE TABLE IF NOT EXISTS templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    slug TEXT NOT NULL UNIQUE,
    is_interactive BOOLEAN DEFAULT FALSE NOT NULL,
    required_role TEXT NOT NULL,
    category_id BIGINT REFERENCES template_categories(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- User templates table
CREATE TABLE IF NOT EXISTS user_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    template_slug TEXT NOT NULL,
    template_data JSONB NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- FOCUS SESSIONS AND WELLNESS
-- =============================================

-- Focus sessions table
CREATE TABLE IF NOT EXISTS focus_sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    duration_minutes INTEGER NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'interrupted')),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- GAMIFICATION SYSTEM
-- =============================================

-- Achievements table
CREATE TABLE IF NOT EXISTS achievements (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    icon TEXT,
    category TEXT,
    points INTEGER DEFAULT 0,
    criteria JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- User achievements table
CREATE TABLE IF NOT EXISTS user_achievements (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    achievement_id UUID REFERENCES achievements(id) ON DELETE CASCADE NOT NULL,
    earned_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, achievement_id)
);

-- =============================================
-- INDEXES FOR PERFORMANCE
-- =============================================

-- User-related indexes
CREATE INDEX IF NOT EXISTS idx_goals_user_id ON goals(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_goal_id ON tasks(goal_id);
CREATE INDEX IF NOT EXISTS idx_conversations_user_id ON conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_documents_user_id ON documents(user_id);
CREATE INDEX IF NOT EXISTS idx_user_templates_user_id ON user_templates(user_id);
CREATE INDEX IF NOT EXISTS idx_focus_sessions_user_id ON focus_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_achievements_user_id ON user_achievements(user_id);

-- Template indexes
CREATE INDEX IF NOT EXISTS idx_templates_slug ON templates(slug);
CREATE INDEX IF NOT EXISTS idx_user_templates_slug ON user_templates(template_slug);

-- Date-based indexes
CREATE INDEX IF NOT EXISTS idx_goals_deadline ON goals(deadline);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_focus_sessions_start_time ON focus_sessions(start_time);

-- =============================================
-- TRIGGERS FOR UPDATED_AT
-- =============================================

-- Function to handle updated_at timestamp
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers for all tables
CREATE TRIGGER handle_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION handle_updated_at();

CREATE TRIGGER handle_goals_updated_at
    BEFORE UPDATE ON goals
    FOR EACH ROW
    EXECUTE FUNCTION handle_updated_at();

CREATE TRIGGER handle_tasks_updated_at
    BEFORE UPDATE ON tasks
    FOR EACH ROW
    EXECUTE FUNCTION handle_updated_at();

CREATE TRIGGER handle_ai_agents_updated_at
    BEFORE UPDATE ON ai_agents
    FOR EACH ROW
    EXECUTE FUNCTION handle_updated_at();

CREATE TRIGGER handle_conversations_updated_at
    BEFORE UPDATE ON conversations
    FOR EACH ROW
    EXECUTE FUNCTION handle_updated_at();

CREATE TRIGGER handle_documents_updated_at
    BEFORE UPDATE ON documents
    FOR EACH ROW
    EXECUTE FUNCTION handle_updated_at();

CREATE TRIGGER handle_template_categories_updated_at
    BEFORE UPDATE ON template_categories
    FOR EACH ROW
    EXECUTE FUNCTION handle_updated_at();

CREATE TRIGGER handle_templates_updated_at
    BEFORE UPDATE ON templates
    FOR EACH ROW
    EXECUTE FUNCTION handle_updated_at();

CREATE TRIGGER handle_user_templates_updated_at
    BEFORE UPDATE ON user_templates
    FOR EACH ROW
    EXECUTE FUNCTION handle_updated_at();

CREATE TRIGGER handle_focus_sessions_updated_at
    BEFORE UPDATE ON focus_sessions
    FOR EACH ROW
    EXECUTE FUNCTION handle_updated_at();

CREATE TRIGGER handle_achievements_updated_at
    BEFORE UPDATE ON achievements
    FOR EACH ROW
    EXECUTE FUNCTION handle_updated_at();

-- =============================================
-- SAMPLE DATA INSERTION
-- =============================================

-- Insert sample AI agents
INSERT INTO ai_agents (name, display_name, description, personality, capabilities, accent_color, system_prompt, model_preference) VALUES
('roxy', 'Roxy', 'Your strategic partner for irreversible decisions using the SPADE framework to build true conviction', 'Strategic and methodical, framework-driven and thorough. Uses strategic decision-making terminology and SPADE framework language.', ARRAY['spade_framework', 'strategic_planning', 'decision_analysis', 'stakeholder_management', 'communication_strategy', 'type1_decisions'], '#6366F1', 'You are Roxy, a Strategic Decision Architect AI who specializes in Type 1 (irreversible) decisions using the SPADE framework. You help users build true conviction for high-stakes strategic choices.', 'gpt-4'),
('blaze', 'Blaze', 'Your performance coach who ignites potential and drives peak performance results with strategic decision frameworks', 'Energetic and motivational, results-driven and systematic. Uses dynamic language and decision framework terminology.', ARRAY['goal_setting', 'time_management', 'motivation', 'performance_tracking', 'cost_benefit_analysis', 'decision_frameworks'], '#F59E0B', 'You are Blaze, a high-energy Performance Coach AI who ignites potential and drives peak performance results. You specialize in strategic decision-making using the Cost-Benefit-Mitigation Matrix framework.', 'gpt-4'),
('echo', 'Echo', 'Your marketing maven who creates compelling content and manages brand presence', 'Creative, trendy, brand-conscious, and audience-focused. Speaks in marketing terminology with creative flair.', ARRAY['content_creation', 'social_media', 'brand_strategy', 'copywriting', 'campaign_management'], '#EC4899', 'You are Echo, a creative marketing maven AI. You excel at content creation, social media strategy, and brand development. You speak with creative flair and understand current trends.', 'gpt-4'),
('glitch', 'Glitch', 'Your tech-savvy problem solver who navigates complex technical challenges and system optimization', 'Analytical, detail-oriented, and solution-focused. Uses technical terminology and systematic problem-solving approaches.', ARRAY['technical_analysis', 'system_optimization', 'problem_solving', 'data_analysis', 'automation'], '#10B981', 'You are Glitch, a tech-savvy problem solver AI. You excel at technical analysis, system optimization, and complex problem-solving. You use systematic approaches and technical expertise.', 'gpt-4'),
('nova', 'Nova', 'Your creative visionary who sparks innovative ideas and breakthrough thinking', 'Imaginative, inspiring, and future-focused. Uses creative language and innovative thinking patterns.', ARRAY['creative_thinking', 'innovation', 'ideation', 'trend_analysis', 'future_planning'], '#8B5CF6', 'You are Nova, a creative visionary AI. You spark innovative ideas and breakthrough thinking. You excel at creative problem-solving and future-focused strategies.', 'gpt-4'),
('zen', 'Zen', 'Your wellness guide who promotes balance, mindfulness, and sustainable growth', 'Calm, mindful, and holistic. Uses wellness terminology and balanced perspective approaches.', ARRAY['wellness', 'mindfulness', 'stress_management', 'work_life_balance', 'sustainable_growth'], '#06B6D4', 'You are Zen, a wellness guide AI. You promote balance, mindfulness, and sustainable growth. You help users maintain well-being while achieving their goals.', 'gpt-4'),
('spark', 'Spark', 'Your rapid-fire idea generator who accelerates brainstorming and creative problem-solving', 'Quick, energetic, and idea-rich. Uses dynamic language and rapid ideation techniques.', ARRAY['brainstorming', 'rapid_prototyping', 'creative_problem_solving', 'idea_generation', 'innovation_sprints'], '#EF4444', 'You are Spark, a rapid-fire idea generator AI. You accelerate brainstorming and creative problem-solving with dynamic energy and quick thinking.', 'gpt-4'),
('sage', 'Sage', 'Your wisdom keeper who provides deep insights and strategic guidance based on experience', 'Wise, thoughtful, and experience-based. Uses philosophical language and strategic wisdom approaches.', ARRAY['strategic_guidance', 'wisdom_sharing', 'experience_analysis', 'mentoring', 'philosophical_insights'], '#6B7280', 'You are Sage, a wisdom keeper AI. You provide deep insights and strategic guidance based on experience and philosophical understanding.', 'gpt-4')
ON CONFLICT (name) DO NOTHING;

-- Insert sample achievements
INSERT INTO achievements (name, title, description, icon, category, points, criteria) VALUES
('first_goal', 'Goal Setter', 'Created your first goal', '🎯', 'goals', 50, '{"goals_created": 1}'),
('task_master', 'Task Master', 'Completed 10 tasks', '✅', 'productivity', 100, '{"tasks_completed": 10}'),
('focus_warrior', 'Focus Warrior', 'Completed 5 focus sessions', '🧘', 'focus', 150, '{"focus_sessions": 5}'),
('ai_collaborator', 'AI Collaborator', 'Had 25 conversations with AI agents', '🤖', 'ai', 200, '{"ai_interactions": 25}'),
('document_organizer', 'Document Organizer', 'Uploaded 10 documents', '📁', 'organization', 100, '{"documents_uploaded": 10}'),
('streak_starter', 'Streak Starter', 'Maintained a 7-day streak', '🔥', 'consistency', 300, '{"daily_streak": 7}'),
('wellness_champion', 'Wellness Champion', 'Logged wellness data for 14 days', '💚', 'wellness', 250, '{"wellness_days": 14}'),
('brand_builder', 'Brand Builder', 'Created your first brand profile', '🎨', 'branding', 150, '{"brand_profiles": 1}'),
('power_user', 'Power User', 'Reached level 10', '⚡', 'progression', 500, '{"user_level": 10}'),
('goal_crusher', 'Goal Crusher', 'Completed 5 goals', '💪', 'goals', 400, '{"goals_completed": 5}')
ON CONFLICT (name) DO NOTHING;

-- Insert sample template categories
INSERT INTO template_categories (category, icon, description) VALUES
('Business Strategy', '🎯', 'Strategic planning and business development templates'),
('Productivity', '⚡', 'Task management and productivity optimization templates'),
('Marketing', '📢', 'Marketing and brand development templates'),
('Wellness', '🧘', 'Wellness and work-life balance templates'),
('Decision Making', '🤔', 'Decision frameworks and analysis templates'),
('Creativity', '🎨', 'Creative thinking and innovation templates')
ON CONFLICT (id) DO NOTHING;

COMMIT;
