-- =============================================
-- Create Templates Schema
-- =============================================

-- Create the table for template categories
CREATE TABLE IF NOT EXISTS template_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  icon TEXT,
  description TEXT
);

-- Create the table for templates
CREATE TABLE IF NOT EXISTS templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  slug TEXT NOT NULL UNIQUE,
  is_interactive BOOLEAN DEFAULT FALSE NOT NULL,
  required_role TEXT NOT NULL,
  category_id BIGINT REFERENCES template_categories(id)
);

-- Create the table for user's saved template data
CREATE TABLE IF NOT EXISTS user_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  template_slug TEXT NOT NULL,
  template_data JSONB NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE template_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_templates ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public read access for template categories and templates
DROP POLICY IF EXISTS "Allow public read access" ON template_categories;
CREATE POLICY "Allow public read access" ON template_categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access" ON templates;
CREATE POLICY "Allow public read access" ON templates FOR SELECT USING (true);

-- Create policies for user_templates (users can only access their own templates)
DROP POLICY IF EXISTS "Users can view their own templates" ON user_templates;
CREATE POLICY "Users can view their own templates" ON user_templates FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own templates" ON user_templates;
CREATE POLICY "Users can insert their own templates" ON user_templates FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own templates" ON user_templates;
CREATE POLICY "Users can update their own templates" ON user_templates FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own templates" ON user_templates;
CREATE POLICY "Users can delete their own templates" ON user_templates FOR DELETE USING (auth.uid() = user_id);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_templates_slug ON templates(slug);
CREATE INDEX IF NOT EXISTS idx_templates_category_id ON templates(category_id);
CREATE INDEX IF NOT EXISTS idx_user_templates_user_id ON user_templates(user_id);
CREATE INDEX IF NOT EXISTS idx_user_templates_template_slug ON user_templates(template_slug);

-- Create trigger for updated_at on user_templates
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_user_templates_updated_at ON user_templates;
CREATE TRIGGER update_user_templates_updated_at
    BEFORE UPDATE ON user_templates
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
