-- Create the table for template categories
CREATE TABLE template_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  icon TEXT,
  description TEXT
);

-- Create the table for templates
CREATE TABLE templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  slug TEXT NOT NULL UNIQUE,
  is_interactive BOOLEAN DEFAULT FALSE NOT NULL,
  required_role TEXT NOT NULL,
  category_id BIGINT REFERENCES template_categories(id)
);

-- Create the table for user's saved template data
CREATE TABLE user_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  template_slug TEXT NOT NULL,
  template_data JSONB NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE template_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_templates ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public read access for template categories and templates
CREATE POLICY "Allow public read access" ON template_categories FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON templates FOR SELECT USING (true);

-- Create policies for user_templates (users can only access their own templates)
CREATE POLICY "Users can view their own templates" ON user_templates FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own templates" ON user_templates FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own templates" ON user_templates FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own templates" ON user_templates FOR DELETE USING (auth.uid() = user_id); 